baseurl: /maidSyncher
safe: true
lsi: false
#markdown: RDiscount
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
pygments: true

